.PHONY: build1 build2 clean

build1:
	cd ./src; gcc main-1.c functions.c mergeSort.c parallelMergeSort.c -o ../lab2_exe;

build2:
	cd ./src; gcc main-2.c functions.c mergeSort.c parallelMergeSort.c -o ../lab2_exe;

clean:
	rm lab2_exe;